#! /bin/sh

# ███████╗██████╗  ██████╗
# ██╔════╝██╔══██╗██╔════╝
# ███████╗██████╔╝██║     
# ╚════██║██╔══██╗██║     
# ███████║██║  ██║╚██████╗
# ╚══════╝╚═╝  ╚═╝ ╚═════╝

pulsar-files -c ~/.config/pulsar/pulsar.conf \
             -c ~/.config/pulsar/pulsar-sources.conf $@