#! /bin/sh

# ██╗    ██╗ █████╗ ██╗     ██╗     
# ██║    ██║██╔══██╗██║     ██║     
# ██║ █╗ ██║███████║██║     ██║     
# ██║███╗██║██╔══██║██║     ██║     
# ╚███╔███╔╝██║  ██║███████╗███████╗
#  ╚══╝╚══╝ ╚═╝  ╚═╝╚══════╝╚══════╝

pulsar-wallpapers -c ~/.config/pulsar/tpulsar.conf \
                  -c ~/.config/pulsar/tpulsar-wallpapers.conf $@