#! /bin/sh

#  █████╗ ██████╗ ██████╗ ███████╗
# ██╔══██╗██╔══██╗██╔══██╗██╔════╝
# ███████║██████╔╝██████╔╝███████╗
# ██╔══██║██╔═══╝ ██╔═══╝ ╚════██║
# ██║  ██║██║     ██║     ███████║
# ╚═╝  ╚═╝╚═╝     ╚═╝     ╚══════╝

pulsar-applications -c ~/.config/pulsar/tpulsar.conf \
                    -c ~/.config/pulsar/tpulsar-applications.conf $@