#! /bin/sh

# ██╗    ██╗███████╗██████╗ 
# ██║    ██║██╔════╝██╔══██╗
# ██║ █╗ ██║█████╗  ██████╔╝
# ██║███╗██║██╔══╝  ██╔══██╗
# ╚███╔███╔╝███████╗██████╔╝
#  ╚══╝╚══╝ ╚══════╝╚═════╝ 

pulsar-list  -c ~/.config/pulsar/pulsar-configs/pulsar.conf \
             -c ~/.config/pulsar/pulsar-configs/pulsar-webbookmarks.conf $@