#! /bin/sh

# ██╗   ██╗██╗██████╗ ███████╗
# ██║   ██║██║██╔══██╗██╔════╝
# ██║   ██║██║██║  ██║███████╗
# ╚██╗ ██╔╝██║██║  ██║╚════██║
#  ╚████╔╝ ██║██████╔╝███████║
#   ╚═══╝  ╚═╝╚═════╝ ╚══════╝

pulsar-files -c ~/.config/pulsar/pulsar-configs/pulsar.conf \
             -c ~/.config/pulsar/pulsar-configs/pulsar-videos.conf $@