#! /bin/sh

# ██╗    ██╗███████╗██████╗ 
# ██║    ██║██╔════╝██╔══██╗
# ██║ █╗ ██║█████╗  ██████╔╝
# ██║███╗██║██╔══╝  ██╔══██╗
# ╚███╔███╔╝███████╗██████╔╝
#  ╚══╝╚══╝ ╚══════╝╚═════╝ 

pulsar-webbookmarks -c ~/.config/pulsar/tpulsar-configs/tpulsar.conf \
                    -c ~/.config/pulsar/tpulsar-configs/tpulsar-webbookmarks.conf $@