#! /bin/sh

# ██╗   ██╗██╗██████╗ ███████╗
# ██║   ██║██║██╔══██╗██╔════╝
# ██║   ██║██║██║  ██║███████╗
# ╚██╗ ██╔╝██║██║  ██║╚════██║
#  ╚████╔╝ ██║██████╔╝███████║
#   ╚═══╝  ╚═╝╚═════╝ ╚══════╝

pulsar-videos -c ~/.config/pulsar/tpulsar-configs/tpulsar.conf \
              -c ~/.config/pulsar/tpulsar-configs/tpulsar-videos.conf $@