#! /bin/sh

# ██████╗ ██████╗  ██████╗      ██╗
# ██╔══██╗██╔══██╗██╔═══██╗     ██║
# ██████╔╝██████╔╝██║   ██║     ██║
# ██╔═══╝ ██╔══██╗██║   ██║██   ██║
# ██║     ██║  ██║╚██████╔╝╚█████╔╝
# ╚═╝     ╚═╝  ╚═╝ ╚═════╝  ╚════╝ 

pulsar-projects -c ~/.config/pulsar/tpulsar-configs/tpulsar.conf \
                -c ~/.config/pulsar/tpulsar-configs/tpulsar-projects.conf $@