#! /bin/sh

# ██╗    ██╗███████╗██████╗ 
# ██║    ██║██╔════╝██╔══██╗
# ██║ █╗ ██║█████╗  ██████╔╝
# ██║███╗██║██╔══╝  ██╔══██╗
# ╚███╔███╔╝███████╗██████╔╝
#  ╚══╝╚══╝ ╚══════╝╚═════╝ 

pulsar-websearch -c ~/.config/pulsar/tpulsar-configs/tpulsar.conf \
                 -c ~/.config/pulsar/tpulsar-configs/tpulsar-websearch.conf $@