#! /bin/sh

# ██╗  ██╗██████╗ ███████╗███████╗
# ╚██╗██╔╝██╔══██╗██╔════╝██╔════╝
#  ╚███╔╝ ██████╔╝█████╗  ███████╗
#  ██╔██╗ ██╔══██╗██╔══╝  ╚════██║
# ██╔╝ ██╗██║  ██║███████╗███████║
# ╚═╝  ╚═╝╚═╝  ╚═╝╚══════╝╚══════╝

pulsar-xresources -c ~/.config/pulsar/tpulsar-configs/tpulsar.conf \
                  -c ~/.config/pulsar/tpulsar-configs/tpulsar-xresources.conf $@