#! /bin/sh

# ███████╗██████╗  ██████╗
# ██╔════╝██╔══██╗██╔════╝
# ███████╗██████╔╝██║     
# ╚════██║██╔══██╗██║     
# ███████║██║  ██║╚██████╗
# ╚══════╝╚═╝  ╚═╝ ╚═════╝

pulsar-sources -c ~/.config/pulsar/tpulsar-configs/tpulsar.conf \
               -c ~/.config/pulsar/tpulsar-configs/tpulsar-sources.conf $@