#! /bin/sh

#  ██████╗███╗   ███╗██████╗ 
# ██╔════╝████╗ ████║██╔══██╗
# ██║     ██╔████╔██║██║  ██║
# ██║     ██║╚██╔╝██║██║  ██║
# ╚██████╗██║ ╚═╝ ██║██████╔╝
#  ╚═════╝╚═╝     ╚═╝╚═════╝ 

pulsar-cmdbookmarks -c ~/.config/pulsar/pulsar-configs/pulsar.conf \
                    -c ~/.config/pulsar/pulsar-configs/pulsar-cmdbookmarks.conf $@