#! /bin/sh

# ██████╗ ██╗ ██████╗███████╗
# ██╔══██╗██║██╔════╝██╔════╝
# ██████╔╝██║██║     ███████╗
# ██╔═══╝ ██║██║     ╚════██║
# ██║     ██║╚██████╗███████║
# ╚═╝     ╚═╝ ╚═════╝╚══════╝

pulsar-pictures -c ~/.config/pulsar/tpulsar-configs/tpulsar.conf \
                -c ~/.config/pulsar/tpulsar-configs/tpulsar-pictures.conf $@