#! /bin/sh

# ██████╗  ██████╗  ██████╗███████╗
# ██╔══██╗██╔═══██╗██╔════╝██╔════╝
# ██║  ██║██║   ██║██║     ███████╗
# ██║  ██║██║   ██║██║     ╚════██║
# ██████╔╝╚██████╔╝╚██████╗███████║
# ╚═════╝  ╚═════╝  ╚═════╝╚══════╝

pulsar-documents -c ~/.config/pulsar/tpulsar-configs/tpulsar.conf \
                 -c ~/.config/pulsar/tpulsar-configs/tpulsar-documents.conf $@